### ISSUE TITLE
Data acquisition independent from GUI

### ISSUE THREAD

**Issue by Who8MyLunch** [drandyhaas/Haasoscope#19]
The main Python module contains all parts of the awesome oscilloscope software tool. I have a project where I'd like to sample a downconverted RF signal having a bandwidth of about 10 MHz. I don't need a GUI. I just want your Python class to be embedded in one of my own project's modules.

Do you have any thoughts about how difficult it might be to separate the GUI and drawing functions from the data acquisition and device control code?

Thanks for making this board available. I love it.

Pierre

**Comment by drandyhaas** [comment]
Hi Pierre,
There's a couple possible ways to run without a gui. The first approach will still load HaasoscopeLib.py and have access to nearly all its functionality, but without a gui. The second approach is very barebones, and does not use the HaasoscopeLib (or Draw) at all.
1)  In HaasoscopeDraw.py you can uncomment "d.domaindrawing=False" in order to not launch the gui. This still goes into the standard event loop, but exits after 50 events. You can surely find in HaasoscopeDraw.py where that happens.
While in the event loop, you can print out things in HaasoscopeDraw.py, e.g. by uncommenting lines like "print d.xydata[0][0][12], d.xydata[0][1][12] # print the x and y data, respectively, for the 13th sample on fast adc channel 0".
These are meant to serve as examples of how to access the scope draw for your own means.
2) Run software/serial_read.py instead. This does a minimal setup of the board, and then reads out one event and prints it out. You could expand upon this code to read out as many events as you like.
Good luck, and don't hesitate to write back here with further questions.
I'm glad you're enjoying the Haasoscope!
Best, Dr. Haas.

**Comment by Who8MyLunch** [comment]
@drandyhaas thanks for the replay, that's that's just what I need to know.
